language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_instal:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
