language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --self-update
  - phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
